POST http://localhost:7072/api/post
Content-Type: application/json

{
  "message": "Post Message"
}

###

GET  http://localhost:7072/api/last

###

GET  http://localhost:7072/api/recent

###

POST http://localhost:7072/api/publish
Content-Type: application/json

{
  "message": "Publish Message"
}

###

POST http://localhost:7072/api/post
Content-Type: application/json

{}

###

POST http://localhost:7072/api/publish
Content-Type: application/json

{}