POST https://grayduck-app.azurewebsites.net/api/post
Content-Type: application/json

{
  "message": "Post Message"
}

###

GET  https://grayduck-app.azurewebsites.net/api/last

###

GET  https://grayduck-app.azurewebsites.net/api/recent

###

POST https://grayduck-app.azurewebsites.net/api/publish
Content-Type: application/json

{
  "message": "Publish Message"
}

###

POST https://grayduck-app.azurewebsites.net/api/post
Content-Type: application/json

{}

###

POST https://grayduck-app.azurewebsites.net/api/publish
Content-Type: application/json

{}