POST  https://grayduck-app.azurewebsites.net/api/hello
Content-Type: text/plain
Access-Control-Allow-Origin: *

Kilroy

###

GET  https://grayduck-app.azurewebsites.net/api/time

###

POST https://grayduck-app.azurewebsites.net/api/publish
Content-Type: text/plain

foobar