POST http://localhost:8080/post
Content-Type: application/json

{
  "message": "Post Message"
}

###

GET  http://localhost:8080/last

###

POST http://localhost:8080/publish
Content-Type: application/json

{
  "message": "Publish Message"
}

###

GET  http://localhost:8080/reset

###

POST http://localhost:8080/post
Content-Type: application/json

{}

###

POST http://localhost:8080/publish
Content-Type: application/json

{}